FROM php:fpm-stretch AS php-hakim

RUN apt update && \
        apt install -y libzip-dev libpng-dev libjpeg-dev libfreetype6-dev && \
        docker-php-ext-install pdo pdo_mysql zip

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
                                                    && docker-php-ext-install gd
