version: "3"

services:
    webserver:
        image: nginx
        container_name: 'nginx-hakim'
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ${PWD}/configs/default.conf:/etc/nginx/conf.d/default.conf
            - ${PWD}/app:/var/www/html
    php:
        container_name: 'php-hakim'
        volumes:
            - ${PWD}/app:/var/www/html
        build:
            context: .
            dockerfile: Dockerfile-php
    database:
        image: mysql
        container_name: 'mysql-hakim'
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1

